<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\uServeCore.CopperMonitor.Application\uServeCore.CopperMonitor.Application.csproj" />
    <ProjectReference Include="..\uServeCore.CopperMonitor.Infrastructure\uServeCore.CopperMonitor.Infrastructure.csproj" />
    <ProjectReference Include="..\uServeCore.CopperMonitor.Domain\uServeCore.CopperMonitor.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
